version: "3"
services: 
#ahora se indican los servicios por el orden en que se quiere que se inicien.

#Por ejemplo, mongo debe estar antes de order.
#mongo: mismo nombre usado en el run.sh de Order y application.properties.
#Se resuelve en una dirección IP.
  mongo:
    image: alfonsomp359/p2gps:db
    deploy:
      replicas: 1 
      resources:
        limits:
          cpus: "0.15"
          #memory: 200M
      restart_policy: 
        condition: none #reinicar el contenedor si falla
    ports:
    volumes:
      - "db-data:/data/db" # para dar persistencia a la sesión
  order:
    image: alfonsomp359/p2gps:order
    depends_on:
      - "mongo"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          #memory: 500M
      restart_policy:
        condition: none
    ports:
  web:
    image: alfonsomp359/p2gps:web
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          #memory: 300M
      restart_policy:
        condition: none
    ports:
      - "8082"
volumes:
   db-data: